// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emitplvzveewaxqigoiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtaXRwbHZ6dmVld2F4cWlnb2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NTk0NTYsImV4cCI6MjA2MTUzNTQ1Nn0.GkctB6GUcG0we4QwLhzL3WPtPjnID608U9h960vdHus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);